name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: aiagent_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Cache NX dependencies
        uses: actions/cache@v3
        with:
          path: .nx/cache
          key: ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}

      - name: Lint
        run: npx nx run-many --target=lint --all

      - name: Type check
        run: npx nx run-many --target=type-check --all

      - name: Test
        run: npx nx run-many --target=test --all
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/aiagent_test
          REDIS_URL: redis://localhost:6379

      - name: Build
        run: npx nx run-many --target=build --all

  docker:
    needs: lint-test-build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API Gateway
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/api-gateway/Dockerfile
          push: true
          tags: |
            your-username/ai-agent-api:latest
            your-username/ai-agent-api:${{ github.sha }}

      - name: Build and push Reminder Service
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/reminder-service/Dockerfile
          push: true
          tags: your-username/ai-agent-reminder:latest
